/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiPublicMondaySyncRouteImport } from './routes/api/public/monday-sync'
import { Route as ApiPublicPainelRouteImport } from './routes/api/public/painel'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicMondaySyncRoute = ApiPublicMondaySyncRouteImport.update({
  id: '/api/public/monday-sync',
  path: '/api/public/monday-sync',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPainelRoute = ApiPublicPainelRouteImport.update({
  id: '/api/public/painel',
  path: '/api/public/painel',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/public/monday-sync': typeof ApiPublicMondaySyncRoute
  '/api/public/painel': typeof ApiPublicPainelRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/public/monday-sync': typeof ApiPublicMondaySyncRoute
  '/api/public/painel': typeof ApiPublicPainelRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/public/monday-sync': typeof ApiPublicMondaySyncRoute
  '/api/public/painel': typeof ApiPublicPainelRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/api/public/monday-sync' | '/api/public/painel'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/api/public/monday-sync' | '/api/public/painel'
  id: '__root__' | '/' | '/api/public/monday-sync' | '/api/public/painel'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiPublicMondaySyncRoute: typeof ApiPublicMondaySyncRoute
  ApiPublicPainelRoute: typeof ApiPublicPainelRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/monday-sync': {
      id: '/api/public/monday-sync'
      path: '/api/public/monday-sync'
      fullPath: '/api/public/monday-sync'
      preLoaderRoute: typeof ApiPublicMondaySyncRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/painel': {
      id: '/api/public/painel'
      path: '/api/public/painel'
      fullPath: '/api/public/painel'
      preLoaderRoute: typeof ApiPublicPainelRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiPublicMondaySyncRoute: ApiPublicMondaySyncRoute,
  ApiPublicPainelRoute: ApiPublicPainelRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
